using UnityEngine;

namespace DungeonGraph
{
    /// <summary>
    /// Component that stores the graph node ID for a generated room
    /// This allows corridors to be regenerated by matching rooms back to their graph nodes
    /// </summary>
    public class RoomNodeReference : MonoBehaviour
    {
        public string nodeId;
        public string nodeTypeName;
    }
}
